name: test-workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Create annotation for build error
        run: echo "::error file=./readme.md,line=1::Missing semicolon"
